### ISSUE TITLE
InnoSetup Preprocessor directives are treated as comments.

### ISSUE THREAD

**Issue by fake-name** [idleberg/InnoSetup-Sublime-Text#3]
I have a `*.iss` file that pretty heavily uses the ISPP to do some build-time string munging and pull out version information from some source files.

This uses the ISPP to do these operations, which are all preceded by `#define`. However, this appears to not be highlighted:

![2015-10-20 10_02_56-issue](https://cloud.githubusercontent.com/assets/1401239/10615474/dd829e66-7714-11e5-8f5d-17be5f325353.png)

It'd be nice if `#define` statements in a .iss file were actually highlighted.

**Comment by idleberg** [comment]
Quick and dirty fix in `5.8.3`. However, what are these: Pascal or Inno syntax?

**Comment by fake-name** [comment]
I honestly have no idea which language they're really a part of.

For that matter, I don't have any idea when pascal executes in an inno-setup file. It looks like it's install-time, but I needed a built-time patch, so I just fidgeted until it worked.

**Comment by idleberg** [comment]
5.9.0 should handle directives much better, give it a try

**Comment by fake-name** [comment]
Yeah, that's a lot nicer. Thanks!
